### ISSUE TITLE
Propose a Documentation Scheme and Workflow

### ISSUE THREAD

**Issue by Brentophillips** [BeehiveNGO/Beta#4]
Propose and establish an initial documentation scheme and workflow.

**Comment by wildaces215** [comment]
What do you mean by documentation scheme?

**Comment by Brentophillips** [comment]
Hey, good timing, I was just working on some basic high-level specs and
feeling frustrated about how to keep them super simple. I was looking
through GitHub and having trouble finding some examples.

What I mean by a documentation scheme is how you'd like best for a novice
coder to spec tasks to get them started, and for us all to agree on how to
format them, where to store them and so forth.

I was thinking I'd loosely outline a task in like three paragraphs to fit
in a GitHub issue, link it to a milestone and provide a link to a markdown
file with more detailed information. I've scratching my head over headings
to use for example: Title, Summary, Design, Context....

What headings would you suggest?

Brent

**Comment by wildaces215** [comment]
Let me get back to you on that.

**Comment by wildaces215** [comment]
Also ask Frederico and Roberto about this, I think they can provide much more insight than me.

**Comment by wildaces215** [comment]
Sorry about the constant revisions, I was trying to think of an answer. I'm new at this stuff sorry about that.

**Comment by roby-boy** [comment]
Hi, I'm Roberto.

Here in github I don't know how to define specs.
By using github as a single source of specs, it's easy so that we don't have docs spreaded in different places. By using other tools (like confluence, jira and so on) the specs can be written with more details, but much effort has been needed. For the moment I would suggest to stay with an easy approach.

The issue headings depend on tasks. 
The first tasks to do are the following (all front-end). 
- "Set up the working environment". With this title the work to do can be not so clear. I have in mind a node environment to manage dependency and to automize building process. From my side, this task can be estimate in 8-10 hours. At the end of this task, just an "Hello world" will be displayed.
- Define the static pages, starting from the most important. Without an UX person or designer, the front-end men should do this stuff. I image these tasks as "Propose landing page" (for example), where the final product is an image jpg or png (using gimp or photoshop or whatever you want) that represent the page. So here, no code is present. The estimate here it is not so simple for me, cause it's not my job but I can try. Moreover my experience suggest that the approvement of the pages will be pass through several attempts, cause the taste is different from one to another.
- After the images (mock-up) have been done, the coding can start. it can be start from static html pages.
